version: '3.8'
services:
  thehive:
    image: strangebee/thehive:5.3
    container_name: thehive
    mem_limit: 512m
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS=-Xms256m -Xmx512m
    volumes:
      - thehive-data:/opt/thp/thehive/data
      - thehive-logs:/var/log/thehive
    networks:
      - soc-net
  shuffle-opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: shuffle-opensearch
    mem_limit: 256m
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - shuffle-db:/usr/share/opensearch/data
    networks:
      - soc-net
  shuffle-backend:
    image: ghcr.io/shuffle/shuffle-backend:latest
    container_name: shuffle-backend
    mem_limit: 512m
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shuffle-apps:/shuffle-apps
    environment:
      - DATASTORE_EMULATOR_HOST=shuffle-opensearch:9200
      - OPENSEARCH_URL=http://shuffle-opensearch:9200
      - SHUFFLE_OPENSEARCH_URL=http://shuffle-opensearch:9200
      - BACKEND_HOSTNAME=shuffle-backend
      - SHUFFLE_ENCRYPTION_MODIFIER=aria_soc_shuffle
      - SHUFFLE_CLOUDRUN_URL=http://shuffle-backend:5001
      - SHUFFLE_DISABLE_CLOUD_SYNC=true
    networks:
      - soc-net
    depends_on:
      - shuffle-opensearch
  shuffle-frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest
    container_name: shuffle-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - BACKEND_HOSTNAME=shuffle-backend
      - SHUFFLE_DISABLE_CLOUD_SYNC=true
    networks:
      - soc-net
    depends_on:
      - shuffle-backend
  shuffle-worker:
    extra_hosts:
      - "shuffle-backend:85.239.231.102"
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: shuffle-worker
    hostname: shuffle-worker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENVIRONMENT_NAME=Shuffle
      - BASE_URL=http://85.239.231.102:5001
      - SHUFFLE_BACKEND_HOSTNAME=85.239.231.102
      - SHUFFLE_BACKEND_PORT=5001
      - DOCKER_API_VERSION=1.40
      - SHUFFLE_BASE_IMAGE_NAME=shuffle
      - SHUFFLE_BASE_IMAGE_REGISTRY=ghcr.io
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX=latest
      - CLEANUP=true
      - ORG_ID=251c3869-a376-476e-94ef-1dfde15a6fbd
      - SHUFFLE_PASS_WORKER_PROXY=false
      - DOCKER_NETWORK=soc-stack_soc-net
      - SHUFFLE_DOCKER_NETWORK_MODE=host
      - SHUFFLE_WORKER_SERVER_URL=http://85.239.231.102:5001
    networks:
      - soc-net
    depends_on:
      - shuffle-backend
volumes:
  thehive-data:
  thehive-logs:
  shuffle-db:
  shuffle-apps:
networks:
  soc-net:
    driver: bridge
